"""maverick_authority_verified.py

Hand-reviewed by Nash, 2026-07-20: scored every one of the 446 entities in
data/processed/maverick_candidate_entities_scored.csv (the top-down candidate
list from src/build_maverick_candidate_list.py -- Wikipedia whistleblower/
conspiracy-theorist categories cross-referenced against corpus frequency).
Result: essentially every candidate confirmed as a genuine maverick-authority
entity -- the whole list is used as-is below.

Scoring criterion, in Nash's words: not strictly "is this a real person" --
organizations functioning as an alternative-authority source count too (e.g.
AE911Truth). Individuals who aren't credentialed experts but are treated as
one within this subculture BECAUSE of their media platform (Alex Jones, Joe
Rogan, Tucker Carlson) count too -- there's a real, deliberately-not-
disentangled overlap between opinion/commentary and research/investigation in
this domain. A second layer separating individual credentialed experts from
platform-driven commentators was considered but deferred -- revisit if it
turns out to matter for the regression.

Two things flagged during review, kept as-is (not excluded):
- Richard Dawkins: noted as "kind of maverick now" -- consistent with
  consensus_experts_verified.py, which independently excluded him from the
  CONSENSUS side as "a combative public commentator, not institutional-
  consensus framing." Not a contradiction between the two lists.
- AE911Truth / Architects & Engineers for 9/11 Truth: same real organization,
  two name variants in the corpus. Both kept deliberately -- different ways
  people actually refer to it in comments, both should match.

This replaces the raw, unaudited entity_final_review.csv
`final_bucket_guess == 'maverick_authority'` bucket (418 entities, ~25% of
actual corpus matches were topic-noise like "New World Order"/"Deep State"/
"Conspiracy Theory" rather than any person or organization -- see
handoff/task_maverick_authority_list_cleanup.md for the full history of how
that contamination happened and why it went unfixed for so long).
"""

VERIFIED_MAVERICK_AUTHORITY = [
    # whistleblower (124)
    "WikiLeaks",
    "Julian Assange",
    "Project Veritas",
    "Edward Snowden",
    "Glenn Greenwald",
    "Aaron Swartz",
    "Michael Hastings",
    "Chelsea Manning",
    "Smedley Butler",
    "Seymour Hersh",
    "Bradley Manning",
    "Sibel Edmonds",
    "Celerino Castillo",
    "Matt Taibbi",
    "William Binney",
    "John Roberts",
    "Deep Throat",
    "Daniel Ellsberg",
    "Barrett Brown",
    "George De Mohrenschildt",
    "Linda Tripp",
    "Mordechai Vanunu",
    "Erin Brockovich",
    "Coleen Rowley",
    "Robert Baer",
    "Karen Silkwood",
    "Mark Felt",
    "Shiv Chopra",
    "Annie Machon",
    "Karen Kwiatkowski",
    "Edward Loomis",
    "Martha Mitchell",
    "Viktor Suvorov",
    "Jeffrey Sterling",
    "Frank Serpico",
    "Ralph McGehee",
    "Harry Markopolos",
    "Joseph Wilson",
    "Michael German",
    "Bassem Youssef",
    "Peter Wright",
    "John White",
    "Frank Snepp",
    "Boris Bazhanov",
    "Frederic Whitehurst",
    "Jeffrey Wigand",
    "Peter Buxtun",
    "Vladimir Bukovsky",
    "Katharine Gun",
    "Arnold Gundersen",
    "Perry Fellwock",
    "Jan Karski",
    "W. Mark Felt",
    "Sherron Watkins",
    "Joe Darby",
    "Jane Turner",
    "Herbert Yardley",
    "A. Ernest Fitzgerald",
    "William Marcus",
    "David Shaylor",
    "Marsha Coleman-Adebayo",
    "Jeffrey Alexander Sterling",
    "William Schumer",
    "Christoph Meili",
    "Nancy Olivieri",
    "David Franklin",
    "Herbert von Bose",
    "Joy Adams",
    "John Paul Vann",
    "Bartolome de las Casas",
    "Clive Ponting",
    "Youri Bandazhevsky",
    "William Sanjour",
    "Allen Mosbaugh",
    "Shannon Doyle",
    "George Galatis",
    "Allan Cutler",
    "Timothy Kerr",
    "George D. Wynalda Jr.",
    "Juan Walterspiel",
    "Alan Parkinson",
    "Paul van Buitenen",
    "Marc Hodler",
    "Marlene Garcia-Esperat",
    "Sarah Thomas",
    "Janet Howard",
    "Tanya Ward Jordan",
    "Joyce E. Megginson",
    "Cynthia Cooper",
    "J. Kirke Wiebe",
    "Neil Patrick Carrick",
    "Mukesh Kapila",
    "Samuel Provance",
    "Renee Dufault",
    "William Tobin",
    "Robert Kobus",
    "Andre Cicolella",
    "Keith A. Schooley",
    "Linda Mitchell",
    "Mark Whitacre",
    "Samuel Shaw",
    "Silas Soule",
    "Edmund Dene Morel",
    "Stanley Adams",
    "Henri Pezerat",
    "Gregory C. Minor",
    "Richard B. Hubbard",
    "Dale G. Bridenbaugh",
    "John Michael Gravitt",
    "Duncan Edmonds",
    "Ingvar Bratt",
    "Cathy Massiter",
    "Ronald J. Goldstein",
    "Roger Wensil",
    "Howard Samuel Nunn",
    "Douglas Plumley",
    "Joseph Macktal",
    "Harry Templeton",
    "Roland Gibeault",
    "Michael Haddle",
    "Douglas D. Keeth",
    "Myron Mehlman",
    "Vera English",
    "Darin Jones",

    # credentialed_advocacy_org (18)
    "AE911Truth",
    "FLCCC",
    "Richard Gage",
    "Pilots for 9/11 Truth",
    "Architects & Engineers for 9/11 Truth",
    "Kevin Barrett",
    "Fluoride Action Network",
    "National Vaccine Information Center",
    "Front Line COVID-19 Critical Care Alliance",
    "Scholars for 9/11 Truth",
    "Discovery Institute",
    "Physicians for Informed Consent",
    "Firefighters for 9/11 Truth",
    "Scientists for 9/11 Truth",
    "Veterans for 9/11 Truth",
    "Lawyers for 9/11 Truth",
    "Political Leaders for 9/11 Truth",
    "Religious Leaders for 9/11 Truth",

    # jfk_theorist (33)
    "Roger Stone",
    "Bill Hicks",
    "Oliver Stone",
    "Jim Marrs",
    "Russ Baker",
    "Jeff Rense",
    "Mae Brussell",
    "Mark Lane",
    "Michael Collins Piper",
    "Dick Gregory",
    "Milton William Cooper",
    "Massimo Mazzucco",
    "L. Fletcher Prouty",
    "David Lifton",
    "Jack Anderson",
    "James DiEugenio",
    "Robert Morrow",
    "Barr McClellan",
    "Madeleine Duncan Brown",
    "Vincent Salandria",
    "Michael Shrimpton",
    "Billie Sol Estes",
    "A. J. Weberman",
    "Marguerite Oswald",
    "Robert J. Groden",
    "Revilo P. Oliver",
    "Richard E. Sprague",
    "Penn Jones Jr.",
    "Roger D. Craig",
    "Thomas N. Downing",
    "Michael Eddowes",
    "Floyd Fithian",
    "Leo Sauvage",

    # 911_theorist (32)
    "David Icke",
    "Jesse Ventura",
    "Cynthia McKinney",
    "Paul Joseph Watson",
    "Webster Tarpley",
    "Michael Ruppert",
    "Steve Pieczenik",
    "David Ray Griffin",
    "Paul Craig Roberts",
    "Philip Giraldi",
    "William Rodriguez",
    "Barbara Honegger",
    "Steven E. Jones",
    "Daniele Ganser",
    "Vanessa Beeley",
    "Kurt Sonnenfeld",
    "Thierry Meyssan",
    "Michel Chossudovsky",
    "Albert Stubblebine",
    "David Shayler",
    "Jim Hoffman",
    "Alan Hart",
    "Barrie Zwicker",
    "L. Lin Wood",
    "Elias Davidsson",
    "Lorie Van Auken",
    "Michael Meacher",
    "Kenneth O'Keefe",
    "John McMurtry",
    "Richard Bergeron",
    "Mathias Brockers",
    "Jim Corr",

    # covid_theorist (18)
    "Russell Brand",
    "Luc Montagnier",
    "Catherine Austin Fitts",
    "Pierre Kory",
    "Michael Yeadon",
    "Alex Berenson",
    "America's Frontline Doctors",
    "Vivek Ramaswamy",
    "Peter Navarro",
    "Stella Immanuel",
    "Charlie Ward",
    "Lara Logan",
    "Li-Meng Yan",
    "Piers Corbyn",
    "Heather Heying",
    "Mikki Willis",
    "Kate Shemirani",
    "Naomi Seibt",

    # antivax (26)
    "Andrew Wakefield",
    "Steve Kirsch",
    "Jenny McCarthy",
    "Judy Mikovits",
    "Naomi Wolf",
    "Sharyl Attkisson",
    "Stephanie Seneff",
    "Brian Hooker",
    "Sherri Tenpenny",
    "Mark Crispin Miller",
    "Peter Breggin",
    "Robert W. Malone",
    "Peter A. McCullough",
    "James Lyons-Weiler",
    "Christiane Northrup",
    "Mark Geier",
    "Dan Burton",
    "Sayer Ji",
    "J. Bart Classen",
    "Boyd Haley",
    "Joseph Ladapo",
    "David Geier",
    "Bernard Rimland",
    "David Avocado Wolfe",
    "H. Hugh Fudenberg",
    "Richard E. Frye",

    # hiv_aids_denialist (20)
    "Kary Mullis",
    "Bret Weinstein",
    "Stefan Lanka",
    "G. Edward Griffin",
    "Peter Duesberg",
    "Lynn Margulis",
    "Joseph Mercola",
    "Gary Null",
    "David Rasnick",
    "Celia Farber",
    "Christine Maggiore",
    "Matthias Rath",
    "James P. Hogan",
    "Harvey Bialy",
    "Phillip E. Johnson",
    "Serge Lang",
    "Tom Bethell",
    "Jad Adams",
    "Henry H. Bauer",
    "Robert Root-Bernstein",

    # ufo_theorist (8)
    "Bob Lazar",
    "Wilhelm Reich",
    "John Lear",
    "Linda Moulton Howe",
    "Haim Eshed",
    "Donald Keyhoe",
    "Bill Moore",
    "Stanton T. Friedman",

    # flat_earth (26)
    "Stew Peters",
    "Tila Tequila",
    "Mark Sargent",
    "Samuel Rowbotham",
    "Lord Jamar",
    "Bryce Mitchell",
    "Mike Hughes",
    "Frank Cherry",
    "Orlando Ferguson",
    "Samuel Shenton",
    "Carl Froch",
    "Wilbur Glenn Voliva",
    "Mohammed Yusuf",
    "Charles K. Johnson",
    "E. W. Bullinger",
    "Kron Gracie",
    "John Jasper",
    "Javi Poves",
    "Shabtai Ambron",
    "Alfio Basile",
    "Elizabeth Lady Blount",
    "Yuri Loza",
    "Branimir Nestorovic",
    "Tyler Owens",
    "Igor Prokopenko",
    "Deacon White",

    # moon_landing_theorist (5)
    "Bart Sibrel",
    "Bill Kaysing",
    "David Percy",
    "Mary Bennett",
    "Una Ronald",

    # chemtrail_theorist (6)
    "Art Bell",
    "Dane Wigington",
    "Clifford Carnicom",
    "William Thomas",
    "Richard Finke",
    "Chris Bovey",

    # pseudoarchaeology (21)
    "Graham Hancock",
    "Helena Blavatsky",
    "Zecharia Sitchin",
    "Robert Schoch",
    "Michael Cremo",
    "Immanuel Velikovsky",
    "Robert Bauval",
    "Ron Wyatt",
    "Erich von Daniken",
    "Giorgio Tsoukalos",
    "Scott Creighton",
    "Ignatius Donnelly",
    "Maurice Cotterell",
    "James Churchward",
    "Louis Pauwels",
    "Jacques Bergier",
    "Richard Cassaro",
    "Barry Fell",
    "Peter Kolosimo",
    "Charles Piazzi Smyth",
    "Augustus Le Plongeon",

    # free_energy_theorist (5)
    "Nikola Tesla",
    "Stanley Meyer",
    "John Searl",
    "Bob Boyce",
    "Daniel Dingel",

    # new_world_order_theorist (2)
    "Adam Weishaupt",
    "Mark Dice",

    # bilderberg_theorist (2)
    "Daniel Estulin",
    "Jim Tucker",

    # mkultra (3)
    "Sidney Gottlieb",
    "Victor Marchetti",
    "Donald Ewen Cameron",

    # qanon (10)
    "Jim Watkins",
    "Austin Steinbart",
    "Ron Watkins",
    "Coleman Rogers",
    "Paul Furber",
    "Martin Geddes",
    "Timothy Charles Holmseth",
    "Tracy Diaz",
    "Jason Gelinas",
    "Robert Cornero Jr.",

    # gmo_theorist (4)
    "Vandana Shiva",
    "Jeffrey M. Smith",
    "Tami Canal",
    "Marie-Monique Robin",

    # intelligent_design (4)
    "Michael Behe",
    "Stephen C. Meyer",
    "William Dembski",
    "Paul Nelson",

    # climate_skeptic_org (7)
    "William Happer",
    "Global Warming Policy Foundation",
    "CO2 Coalition",
    "Patrick Michaels",
    "John Clauser",
    "Gregory Wrightstone",
    "William O'Keefe",

    # sandy_hook_theorist (1)
    "Wolfgang Halbig",

    # epstein_journalist (4)
    "Whitney Webb",
    "Vicky Ward",
    "Julie K. Brown",
    "Roger Sollenberger",

    # rogan_guest_scientist (12)
    "Joe Rogan",
    "Neil deGrasse Tyson",
    "Richard Dawkins",
    "Michio Kaku",
    "Paul Stamets",
    "Avi Loeb",
    "Rhonda Patrick",
    "Brian Cox",
    "Andrew Huberman",
    "Garry Nolan",
    "Sean Carroll",
    "Carole Hooven",

    # misc_theorist (1)
    "Jay Weidner",

    # conspiracy_general (54)
    "Alex Jones",
    "Tucker Carlson",
    "Tulsi Gabbard",
    "Rudy Giuliani",
    "Matt Gaetz",
    "Michael Flynn",
    "David Duke",
    "Nick Fuentes",
    "Gary Allen",
    "Del Bigtree",
    "Max Blumenthal",
    "Mike Adams",
    "Robert F. Kennedy Jr.",
    "Ann Coulter",
    "Robert David Steele",
    "Ben Garrison",
    "Danny Casolaro",
    "Jerome Corsi",
    "F. William Engdahl",
    "Mike Cernovich",
    "Jim Garrison",
    "Joe Arpaio",
    "Dinesh D'Souza",
    "Roseanne Barr",
    "Thomas Cowan",
    "Dan Bilzerian",
    "Simone Gold",
    "Rashid Buttar",
    "Jim Caviezel",
    "Shiva Ayyadurai",
    "Louie Gohmert",
    "James Fetzer",
    "Ali Alexander",
    "Pamela Geller",
    "Seth Abramson",
    "Dave Emory",
    "Andrew Anglin",
    "Frank Gaffney",
    "Kelly Brogan",
    "Steven Anderson",
    "Ed Asner",
    "Kristen Breitweiser",
    "David Hatcher Childress",
    "Ty Bollinger",
    "Christopher Cantwell",
    "Jack Cashill",
    "Bryan Fischer",
    "Kathy Barnette",
    "Robert Gregory Bowers",
    "Robert M. Bowman",
    "Patrick M. Byrne",
    "Matthew Bracken",
    "Norman G. Baker",
    "James Ellison",
]

UNAMBIGUOUS_MAVERICK_ALIASES = [
    "Snowden", "Assange", "Icke", "Greenwald", "Hersh", "Ellsberg", "Lazar",
    "Taibbi", "Taibi", "Wakefield", "Mullis", "Mikovits", "Yeadon", "Brand",
    "Ventura", "Ganser", "Tarpley", "Ruppert", "Pieczenik", "Chossudovsky",
    "Meyssan", "Kory", "Kirsch", "Seneff", "Buttar", "Tenpenny", "Breggin",
    "McCullough", "Ladapo", "Sitchin", "Velikovsky", "Bauval", "Daniken",
    "von Daniken", "Tsoukalos", "Halbig", "Hancock"
]

VERIFIED_MAVERICK_AUTHORITY.extend(UNAMBIGUOUS_MAVERICK_ALIASES)

